version: '3.7'
services:
    app:
        restart: unless-stopped
        build:
            context: .
        networks:
            - web
        env_file:
            - ./.env
        volumes:
            - ./index.php:/app/index.php
        logging:
            driver: 'json-file'
            options:
                max-size: '50m'
networks:
    web:
        external: true
        name: web
