{
 "title": "TBank Profile",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "portfolio{label=\"totalAmountCurrencies\"}",
     "legendFormat": "Валюты"
    },
    {
     "expr": "portfolio{label=\"totalAmountEtf\"}",
     "legendFormat": "Фонды"
    },
    {
     "expr": "portfolio{label=\"totalAmountShares\"}",
     "legendFormat": "Акции"
    },
    {
     "expr": "portfolio{label=\"totalAmountBonds\"}",
     "legendFormat": "Облигации"
    },
    {
     "expr": "portfolio{label=\"totalAmountFutures\"}",
     "legendFormat": "Фьючерсы"
    }
   ]
  },
  {
   "title": "Позиции портфеля",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "positions_count * positions_price",
     "legendFormat": "{{ticker}}"
    }
   ]
  },
  {
   "title": "Заявки",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 5 },
   "targets": [
    {
     "expr": "order_totals{direction=\"ORDER_DIRECTION_BUY\"}",
     "legendFormat": "{{ticker}} BUY"
    },
    {
     "expr": "order_totals{direction=\"ORDER_DIRECTION_SELL\"}",
     "legendFormat": "{{ticker}} SELL"
    }
   ]
  },
  {
   "title": "Котировки",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "price", "legendFormat": "{{ticker}}" }
   ]
  },
  {
   "title": "Сравнение (24ч)",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg_over_time((delta(price[24h]) / (price - delta(price[24h])))[5m:5s]) * 100",
     "legendFormat": "{{ticker}}"
    }
   ]
  }
 ]
}